name: app/build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -f build/Dockerfile -t app-web:latest .

      - name: Run Tests
        run: |
          container_id=$(docker run -d -p 8080:8080 app-web:latest)
          timeout=10
          counter=0
          until nc -z localhost 8080; do
            sleep 1
            counter=$((counter+1))
            if [ $counter -ge $timeout ]; then
              echo "Timeout reached. Port not available."
              docker logs "$container_id" && docker stop "$container_id"
              exit 1
            fi
          done
          response=$(curl -s http://localhost:8080/)
          echo $response

