name: app/build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -f build/Dockerfile -t app-web:latest .

      - name: Run Tests
        run: |
          # start service
          container_id=$(docker run -d -p 8080:8080 app-web:latest)
          # wait start
          timeout=10
          counter=0
          until [ "$(curl -o /dev/null -s -w '%{http_code}' http://localhost:8080/)" -eq 200 ]; do
            sleep 1
            counter=$((counter+1))
            if [ $counter -ge $timeout ]; then
              echo "Timeout reached. HTTP check failed."
              docker logs "$container_id" && docker stop "$container_id"
              exit 1
            fi
          done
          # tests
          response=$(curl -s http://localhost:8080/)
          echo $response
