name: infra/build

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/infra-**"
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options:
          - plan
          - apply
        required: false
        default: 'plan'

concurrency:
  group: infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure
        run: |
          cp -v infra/vars/infra.tfvars.dist infra/vars/infra.tfvars

      - name: Run Terraform
        env:
          TF_VAR_GITHUB_TOKEN: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
        run: |
          ACTION="${{ github.event.inputs.action }}"
          if [ -z "$ACTION" ]; then
            ACTION="plan"
          fi
          echo "Running terraform action: $ACTION"
          ./infra/run "$ACTION"
