name: infra/build

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        options:
          - app
          - common
          - core
        required: false
        description: 'terraform stack'
        default: 'common'
      action:
        type: choice
        options:
          - plan
          - apply
        required: false
        description: 'terraform action'
        default: 'plan'

concurrency:
  group: infra-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Terraform/Plan - common
        env:
          STACK: "common"
          ENV: "dev"
          ACTION: "${{ github.event.inputs.action }}"
          # tfvars
          TF_VAR_github_token: "${{ secrets.TF_VAR_GITHUB_TOKEN }}"
          TF_VAR_dockerhub_username: "${{ secrets.DOCKERHUB_USERNAME }}"
          TF_VAR_dockerhub_token: "${{ secrets.DOCKERHUB_TOKEN }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          echo "[${ACTION}] STACK="${STACK}" ENV="${ENV}""
          cd infra/
          touch "stacks/$STACK/vars/${ENV}.tfvars"
          make "${ACTION}" STACK="${STACK}" ENV="${ENV}"
