name: infra/build

on:
  #  push:
  #    paths:
  #      - "infra/**"
  #      - ".github/workflows/infra-**"
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options:
          - plan
          - apply
        required: false
        description: 'terraform action'
        default: 'plan'

concurrency:
  group: infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Terraform/Plan - common
        env:
          STACK: "common"
          ENV: "dev"
          ACTION: "${{ github.event.inputs.action }}"
          # tfvars
          TF_VAR_dockerhub_username: "${{ secrets.TF_VAR_GITHUB_TOKEN }}"
          TF_VAR_dockerhub_token: "${{ secrets.TF_VAR_GITHUB_TOKEN }}"
          TF_VAR_github_token: "${{ secrets.TF_VAR_GITHUB_TOKEN }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          cd infra/
          touch "stacks/$STACK/vars/${ENV}.tfvars"
          make plan STACK="${STACK}" ENV="${ENV}"
